### ISSUE TITLE
Haddock build failure

### ISSUE THREAD

**Issue by snoyberg** [solatis/haskell-network-anonymous-tor#1]
```
src/Network/Anonymous/Tor.hs:(149,41)-(150,83):
    parse error on input ‘-- | Port the Tor control server is listening at. Use
                                        --   'detectPort' to probe possible ports.^M’
```

**Comment by solatis** [comment]
That also explains why the hackage docs are not being generated. Will fix ASAP.

**Comment by solatis** [comment]
I've just pushed version 0.9.1 to hackage which fixes this issue. I'll monitor hackage whether the docs come online soon, and if so, will close this issue.

Sorry for the inconvenience.

**Comment by snoyberg** [comment]
No problem, thanks for the quick fix
