### ISSUE TITLE
Improve the TorError type

### ISSUE THREAD

**Issue by froozen** [solatis/haskell-network-anonymous-tor#2]
The current `TorError` type, especially the `ProtocolError`, don't provide enough information to find out what went wrong.

**Comment by solatis** [comment]
I agree with you -- ProtocolError should ideally be amended with some details about what exactly went wrong, where possible.

If you send a pull request, I'l happily merge any improvements.

**Comment by froozen** [comment]
I'll try to implement that and send a pull request.

**Comment by solatis** [comment]
Thanks! I'm a bit busy with other projects at the moment, but if you have any questions I can help you out with, let me know.
